# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 745ad7871cb58434a52fb3c68bad000388366cdb730ad916fc83340bb9c6fca18cc3904e27f941f20e810db54050d6f79b5499ddace872db5060ea6be3e56337

test:
  secret_key_base: 2c10296e2beacb9e51a079a2553ca7efbbf9d6377e0ae9c54f140f7d82303ca0f0de66d666c7b5e33c092895e922769de0549d3b9e57e6d998e6b0254564bccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
